src/main/java/faang/school/urlshortenerservice/utils/Base62Encoder.java, src/test/java/faang/school/urlshortenerservice/utils/Base62EncoderTest.java
=> created encoder base62

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
1. прошу уделить внимание на возвращаемый тип в контроллере и сервисе, если нужно дтошку, то поправлю
2. насчет 302 http ответа, достаточно ли будет аннотации над методом?
=> original link

src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java
=> add UrlService and Hash

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/hash_url_V001__initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> Add DB structure

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/service/UrlShortenerService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/hash_url_V001__initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> Add Base62Encoder

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/config/context/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__hash_url_init.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> Генерация хэша

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__hash_url_init.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> Создать структуру БД

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/config/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__hash_url_init.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> Создание оригинальной ссылки

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/config/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/validator/url/UrlConstraint.java, src/main/java/faang/school/urlshortenerservice/validator/url/UrlValidator.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__hash_url_init.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> Создание короткой ссылки

src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__hash_url_init.sql, src/main/resources/db/changelog/db.changelog-master.yaml
[Генерация списка хэшей](https://github.com/CorporationX/url_shortener_service/pull/108)
=> Генерация списка хэшей

src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__hash_url_init.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Работа с базой(HashRepository)
=> Работа с базой(HashRepository)

src/main/resources/db/changelog/changeset/url_V001__initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Task: https://faang-school.atlassian.net/browse/BJS2-17166
Create DB structure
=> BJS2-17166: Create DB structure

src/main/java/faang/school/urlshortenerservice/config/executor/ThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/model/Hash.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/service/HashService.java, src/main/java/faang/school/urlshortenerservice/service/impl/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/service/impl/HashServiceImpl.java, src/main/resources/application.yaml
Task: https://faang-school.atlassian.net/browse/BJS2-17304
=> BJS2-17304: Generate batch

src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepositoryJdbc.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/url_V001__initial.sql
Task: https://faang-school.atlassian.net/browse/BJS2-17167
Working with DB (HashRepository)
=> BJS2-17167: Working with DB (HashRepository)

src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java
Task: https://faang-school.atlassian.net/browse/BJS2-17302
=> BJS2-17302: Hash repo

src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlCreatedRequest.java, src/main/java/faang/school/urlshortenerservice/dto/UrlCreatedResponse.java, src/main/java/faang/school/urlshortenerservice/model/Url.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/service/impl/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/service/impl/UrlServiceImpl.java, src/main/resources/application.yaml
Task: https://faang-school.atlassian.net/browse/BJS2-17306
=> BJS2-17306: Create short url

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/exception/NotFoundException.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/service/impl/UrlServiceImpl.java
Task: https://faang-school.atlassian.net/browse/BJS2-17308
=> BJS2-17308: Get url

src/main/java/faang/school/urlshortenerservice/exception/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/handler/UrlExceptionHandler.java
Task: https://faang-school.atlassian.net/browse/BJS2-17309
=> BJS2-17309: Exception handler

src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/service/impl/HashCache.java, src/main/java/faang/school/urlshortenerservice/service/impl/UrlServiceImpl.java, src/main/resources/application.yaml
Task: https://faang-school.atlassian.net/browse/BJS2-17303
=> BJS2-17303: Add cleaner

src/main/java/faang/school/urlshortenerservice/config/HashConfig.java, src/main/java/faang/school/urlshortenerservice/controller/HashController.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepositoryJdbc.java, src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/HashGeneratorTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-17165
Cache generation
=> BJS2-17165: Cache generation

src/main/java/faang/school/urlshortenerservice/controller/HashController.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepositoryJdbc.java, src/main/java/faang/school/urlshortenerservice/service/HashCache.java, src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/HashCacheTest.java, src/test/java/faang/school/urlshortenerservice/service/HashGeneratorTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-17164
Caching free hashes
=> BJS2-17164: Caching free hashes

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-17162
Creating an original link
=> BJS2-17162: Creating an original link

src/main/java/faang/school/urlshortenerservice/handler/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/handler/UrlExceptionHandler.java
Task: https://faang-school.atlassian.net/browse/BJS2-17161
Exception handler
=> BJS2-17161: Exception handler

src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/schedule/CleanerScheduler.java, src/main/resources/application.yaml
Task: https://faang-school.atlassian.net/browse/BJS2-17159
Job to free unused hashes
=> BJS2-17159: Job to free unused hashes

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/handlers/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/service/UrlServiceImpl.java
=> Mpo feature bjs2 17131

build.gradle.kts, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/handlers/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/service/UrlServiceImpl.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/encoder/Base62EncoderTest.java, src/test/java/faang/school/urlshortenerservice/generator/HashGeneratorTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceImplTest.java
=> Добавил функцию получения оригинальной ссылки из hash

src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
feature 17252 Работа с базой(HashRepository). Реализовал логику HashRepository, протестировал через postman, DBeaver.
=> feature 17252 Работа с базой(HashRepository)

src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/Base62EncoderTest.java
feature 17254 Генерация списка хэшей. Реализовал генерацию списка хэшей, написал unit тесты, протестировал с помощью postman.
=> feature 17254 Генерация списка хэшей

src/main/java/faang/school/urlshortenerservice/config/ThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/hashservice/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/hashservice/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/service/Base62Encoder.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/Base62EncoderTest.java, src/test/java/faang/school/urlshortenerservice/service/hashservice/Base62EncoderTest.java, src/test/java/faang/school/urlshortenerservice/service/hashservice/HashGeneratorTest.java
feature 17255 Генерация хэша. Реализовал логику генерации хэша, написал unit тесты, протестировал с помощью postman, DBeaver.
=> feature 17255 Генерация хэша

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/exception/DataUrlValidationException.java, src/main/java/faang/school/urlshortenerservice/exception/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/exception/GlobalExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/validator/UrlValidator.java, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java, src/test/java/faang/school/urlshortenerservice/validator/UrlValidatorTest.java
feature 17251 Создание оригинальной ссылки. Реализовал логику создания оригинальной ссылки и редиректа по ней, так же сделал обработчик исключений из задачи 17253. Написал unit тесты, протестировал через postman, Dbeaver.
=> feature 17251 Создание оригинальной ссылки. 

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/exception/DataUrlValidationException.java, src/main/java/faang/school/urlshortenerservice/exception/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/exception/GlobalExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/validator/UrlValidator.java, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java, src/test/java/faang/school/urlshortenerservice/validator/UrlValidatorTest.java
feature 17253 Реализовал логику обработки исключений, протестировал через postman
=> feature 17253 Реализовал логику обработки исключений, протестировал через postman

src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/sheduler/CleanerScheduler.java, src/main/resources/application.yaml
feature 17256 Джоб для освобождения неиспользуемых хэшей. Реализовал логику очистки таблицы url от старых хэшей и добавление их в таблицу hash. Протестировал через postman, Dbeaver
=> feature 17256 Джоб для освобождения неиспользуемых хэшей

src/main/java/faang/school/urlshortenerservice/encoder/Base62.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62EncoderImpl.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/generator/HashGeneratorImpl.java, src/main/java/faang/school/urlshortenerservice/model/Hash.java, src/main/java/faang/school/urlshortenerservice/model/Url.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/HashCash.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/encoder/Base62Test.java
Зафиксировал состояние (все работает в первом приближении). Без тестов.
=> fix commit

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
+ Создал repository HashRepository
+ Создал методы getUniqueValues и getHashBatch
=> BJS2-28074 - Работа с базой(HashRepository)

src/main/java/faang/school/urlshortenerservice/config/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/service/HashGenerator.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/url_shortener_V001_initial.sql, src/test/java/faang/school/urlshortenerservice/repository/HashRepositoryTest.java, src/test/java/faang/school/urlshortenerservice/service/HashGeneratorTest.java
- поменял sql скрипт
- поставил модификатор доступа в метод encoder
=> Генерация хэша + Изменения:

src/main/java/faang/school/urlshortenerservice/config/HashThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/encoder/BaseEncoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashJpaRepository.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
+ Создал baseEncoder для представления чисел в виде кеша.
+ Создал HashRepository для получения уникальных последовательностей, вставки батчем, получения батчем.
+ Сконфигурировал кастомный ThreadPool для Hash.
=> BJS2-28071 - Генерация хэша

src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
Create Entity Hash
Create HashRepository
add application.yaml property batch_size
=> feature-BJS2-28124 Work with DB(HashRepository)

src/main/java/faang/school/urlshortenerservice/encoder/BaseEncoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/resources/application.yaml
+ Сделал baseEncoder более гибким.
=> BJS2-28076 - Генерация Списка хэшей

src/main/java/faang/school/urlshortenerservice/util/Base62Encoder.java, src/test/java/faang/school/urlshortenerservice/util/Base62EncoderTest.java
- Added Base62Encoder component to encode a list of numbers into unique Base62 strings
=> BJS2-28106 - Генерация списка хэшей

src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
- Added batch operations for hash retrieval and deletion
=> BJS2-28104 - Работа с базой(HashRepository)

src/main/java/faang/school/urlshortenerservice/config/ExecutorConfig.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/resources/application.yaml
- Created `HashGenerator` which handles the generation and processing of hash batches
- Created `ExecutorConfig` which configures a custom thread pool executor for asynchronous processing
=> BJS2-28101 - Генерация хэша

src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/config/hash/HashCacheConfig.java, src/main/java/faang/school/urlshortenerservice/config/hash/HashConfig.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/resources/application.yaml
+ Добавил класс Cache для доступа к закешированным hash'ам
=> BJS2-28077 - Кэширование свободных хэшей

src/main/java/faang/school/urlshortenerservice/config/ExecutorConfig.java, src/main/java/faang/school/urlshortenerservice/config/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/exception/EntityNotFoundException.java, src/main/java/faang/school/urlshortenerservice/model/Url.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml
- Add `EntityNotFoundException`: Custom exception for handling scenarios where an entity is not found, with improved error logging.
- Add `RedisConfig`: Configuration for Redis with `JedisConnectionFactory`, including beans for `RedisConnectionFactory`, `RedisTemplate`, and `CacheManager`.
- Add `Url` entity: Class for storing URL data, including fields for hash, URL, and creation timestamp.
- Add `UrlController`: Controller for handling GET requests to redirect based on a hash value.
- Add `UrlRepository`: Repository interface for CRUD operations on the `Url` entity, with a custom method to find URLs by hash.
- Add `UrlService`: Service class for managing URL operations, including caching and retrieval of long URLs based on hash values.
=> BJS2-28102 - Создание оригинальной ссылки

src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/resources/application.yaml
- Created HashCache, which performs internal caching of available hashes, asynchronously fills this cache without blocking requests and is fully thread-safe.
=> BJS2-28107 - Кэширование свободных хэшей

src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
- Implemented POST /url endpoint to accept a DTO with a long URL in the request body.
- Added validation in the controller to ensure the provided URL is valid.
- Implemented UrlService to obtain the URL, request a hash from HashCache, and save the hash-URL association in both the database and Redis.
- Configured UrlRepository for database persistence and UrlCacheRepository for Redis caching.
=> BJS2-28105 - Создание короткой ссылки

src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/config/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/encoder/BaseEncoder.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java, src/main/java/faang/school/urlshortenerservice/repository/hash/HashJpaRepository.java, src/main/java/faang/school/urlshortenerservice/repository/hash/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/url_V002_hash_index.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
+ Создал контроллер для создания коротких ссылок.
+ Добавил кеширование новых ссылок на определенное время.
+ Создал репозиторий для управления Url'ами.
+ Добавил сервисную логику.
+ Прописал тесты на контроллер и сервис
=> BJS2-28075 - Создание короткой ссылки

src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/encoder/Base62EncoderTest.java
Create Base62Encoder
Create Base62EncoderTest
add application.yaml property base62Charset
=> feature-BJS2-28126 Generation list of hashes

src/test/java/faang/school/urlshortenerservice/scheduler/CleanerSchedulerTest.java
- Added unit test for CleanerScheduler
=> BJS2-28108 - Джоб для освобождения неиспользуемых хэшей

src/main/java/faang/school/urlshortenerservice/config/AppConfig.java, src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java, src/main/resources/application.yaml
Create HashGenerator
Create AppConfig
add application.yaml property executor.batch_size
=> Feature bjs2 28121

src/main/java/faang/school/urlshortenerservice/service/UrlService.java
Reverts CorporationX/url_shortener_service#448
=> Revert "fin"

src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/resources/application.yaml
Create HashCash
Create AppConfig
add application.yaml property hash.queue_capacity,hash.min_fill_percent
=> Feature bjs2 28127

src/main/java/faang/school/urlshortenerservice/repository/url/UrlJpaRepository.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
+ Создал CleanerScheduler для запланированного ежедневного освобождения неиспользуемых хешей.
=> BJS2-28078 - Джоб для освобождения неиспользуемых хэшей

src/main/java/faang/school/urlshortenerservice/dto/ErrorResponseDto.java, src/main/java/faang/school/urlshortenerservice/handler/GlobalExceptionHandler.java
+ Создал GlobalExceptionHandler для обработки исключений.
+ Создал ErrorResponseDto как ответ пользователю при возникновении исключительных случаев.
=> BJS2-28079 - Обработчик исключений

src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java, src/main/java/faang/school/urlshortenerservice/config/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDtoRequest.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/mapper/UrlMapper.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/repository/redis/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
Create UrlController
Create UrlRepository
Create RedisConfig
Create UrlEntity
Create Dto
=> Feature bjs2 28125 Create short url

src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/resources/db/changelog/changeset/url_shortener_V001_initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Add tables hash, url and sequence
=> Add tables hash, url and sequence

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/cashe/HashCash.java, src/main/java/faang/school/urlshortenerservice/hash_generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
add method in UrlRepository removeOldUrlAndGetHashes;
add method in UrlService deleteOldUrls;
Create CleanerScheduler;
=> feature-BJS2-28122 Job to free unused hashes

src/main/java/faang/school/urlshortenerservice/exception/ValidationException.java, src/main/java/faang/school/urlshortenerservice/handler/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/handler/UrlExceptionHandler.java
add ErrorResponse;
add UrlExceptionHandler;
add ValidationException:
=> feature-BJS2-28122 Exception handler

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/UrlShortenerServiceApplication.java, src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/config/context/AsyncGeneratorConfig.java, src/main/java/faang/school/urlshortenerservice/config/context/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/exception/EntityNotFoundException.java, src/main/java/faang/school/urlshortenerservice/exception/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/exception/GlobalExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/V001__init.sql, src/main/resources/db/changelog/changeset/V001__init.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/urlshortenerservice/service/HashCacheTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
=> Feature bjs2 28209 url shortener full

src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
=> Minotaur master bc5 maksim don bjs2 28194

src/main/java/faang/school/urlshortenerservice/config/async/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
Add HashGenerator with AsyncConfig
=> Minotaur master bc5 maksim don bjs2 28196

src/main/java/faang/school/urlshortenerservice/config/async/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashCache.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/resources/application.yaml
=> Minotaur master bc5 maksim don bjs2 28191

src/main/java/faang/school/urlshortenerservice/config/async/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlRequestDto.java, src/main/java/faang/school/urlshortenerservice/dto/UrlResponseDto.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashCache.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml
=> Minotaur master bc5 maksim don bjs2 28195

src/main/java/faang/school/urlshortenerservice/config/async/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlRequestDto.java, src/main/java/faang/school/urlshortenerservice/dto/UrlResponseDto.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashCache.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml
=> Minotaur master bc5 maksim don bjs2 28193

src/main/java/faang/school/urlshortenerservice/config/async/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlRequestDto.java, src/main/java/faang/school/urlshortenerservice/dto/UrlResponseDto.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/generator/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/generator/HashCache.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application.yaml
=> Minotaur master bc5 maksim don bjs2 28192

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001_urlshortener_service_url.sql, src/main/resources/db/changelog/changeset/V001_urlshortener_service_url_hash.sql, src/main/resources/db/changelog/changeset/V002_urlshortener_service_hash.sql, src/main/resources/db/changelog/changeset/V003_urlshortener_service_sequence.sql, src/main/resources/db/changelog/db.changelog-master.yaml
- Создана миграция для ликвибейс на создание таблиц hash и url
- Созданы соответствующие сущности
=> BJS2-27888

.github/workflows/ci.yml, Dockerfile, build.gradle.kts, src/main/java/faang/school/urlshortenerservice/config/context/UserHeaderFilter.java, src/main/resources/application.yaml, src/main/resources/checkstyle/checkstyle.xml, src/main/resources/dtds/configuration_1_3.dtd, src/test/java/faang/school/urlshortenerservice/util/BaseContextTest.java
Pre configs ci, checkstyle, some small fixes
=> BJS2-43098 pre configs

src/main/resources/db/changelog/changeset/V001_url_shortener_service_DDL.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> - Liquibase initial setup, added url, hash, sequence BJS2-42686

src/main/java/faang/school/urlshortenerservice/config/properties/HashProperties.java, src/main/java/faang/school/urlshortenerservice/model/hash/Hash.java, src/main/java/faang/school/urlshortenerservice/model/url/Url.java, src/main/java/faang/school/urlshortenerservice/repository/hash/HashRepository.java, src/main/resources/application.yaml
- added Hash, Url entities, HashRepository, 2 batch queries methods, config class, refactored application.yaml
=> BJS2-42688

src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/model/hash/Hash.java, src/test/java/faang/school/urlshortenerservice/encoder/Base62EncoderTest.java
- added Base62Encoder class
- added encode method to encode numbers for Hashes
- added simple Hash entity to use in test
=> BJS2-42691 Base62Encoder

src/main/java/faang/school/urlshortenerservice/exception/handler/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/exception/response/ErrorResponse.java
- Added global exception handler plus Error Response class
=> BJS2-42683 Global Exception Handler

src/main/java/faang/school/urlshortenerservice/cleaner/url/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/config/properties/url/UrlProperties.java, src/main/java/faang/school/urlshortenerservice/exception/handler/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/exception/response/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/model/url/Url.java, src/main/java/faang/school/urlshortenerservice/repository/hash/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/cleaner/url/CleanerSchedulerTest.java
- added CleanerScheduler for old urls to reuse their hashes again 
- tests
- some refactor for entities
=> BJS2-42681 Cleaner

src/main/java/faang/school/urlshortenerservice/cache/hash/HashCache.java, src/main/java/faang/school/urlshortenerservice/cleaner/url/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/config/executor/HashThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/config/properties/hash/HashProperties.java, src/main/java/faang/school/urlshortenerservice/config/properties/url/UrlProperties.java, src/main/java/faang/school/urlshortenerservice/exception/handler/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/exception/response/ErrorResponse.java, src/main/java/faang/school/urlshortenerservice/generator/hash/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/model/url/Url.java, src/main/java/faang/school/urlshortenerservice/repository/hash/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/cache/hash/HashCacheIntegrationTest.java, src/test/java/faang/school/urlshortenerservice/cleaner/url/CleanerSchedulerTest.java, src/test/java/faang/school/urlshortenerservice/generator/hash/HashGeneratorIntegrationTest.java
Added HashCache + tests, refactrored some logic
=> Feature bjs2 42682

src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001.sql, src/main/resources/db/changelog/db.changelog-master.yaml
https://faang-school.atlassian.net/browse/BJS2-42715
=> BJS2-42715: Создание структуры БД

build.gradle.kts, src/main/java/faang/school/urlshortenerservice/cache/hash/HashCache.java, src/main/java/faang/school/urlshortenerservice/cleaner/url/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/config/executor/HashThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/config/executor/rejection/CustomCallerRunsPolicy.java, src/main/java/faang/school/urlshortenerservice/config/properties/redis/RedisProperties.java, src/main/java/faang/school/urlshortenerservice/config/properties/url/UrlProperties.java, src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfiguration.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/LongUrlDto.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/exception/handler/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/generator/hash/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/hash/CustomHashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/hash/CustomHashRepositoryImpl.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/url/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/url/UrlService.java, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/cache/hash/HashCacheIntegrationTest.java, src/test/java/faang/school/urlshortenerservice/cleaner/url/CleanerSchedulerTest.java, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/encoder/Base62EncoderTest.java, src/test/java/faang/school/urlshortenerservice/generator/hash/HashGeneratorIntegrationTest.java, src/test/java/faang/school/urlshortenerservice/service/url/UrlServiceTest.java, src/test/java/faang/school/urlshortenerservice/util/BaseContextTest.java
- added Redis, UrlController, fixes on tests, UrlService, logic on url shortner
=> Feature bjs2 42698

src/main/java/faang/school/urlshortenerservice/UrlShortenerApplication.java, src/main/java/faang/school/urlshortenerservice/config/AsyncThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/exception/DataValidationException.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/service/HashService.java, src/main/java/faang/school/urlshortenerservice/util/BaseEncoder.java, src/main/java/faang/school/urlshortenerservice/util/HashGenerator.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/HashServiceTest.java, src/test/java/faang/school/urlshortenerservice/util/BaseEncoderTest.java, src/test/java/faang/school/urlshortenerservice/util/HashGeneratorTest.java
custom thread pool for @Async hash generation
tests
=> add HashGenerator

src/main/java/faang/school/urlshortenerservice/UrlShortenerApplication.java, src/main/java/faang/school/urlshortenerservice/config/AsyncThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/exception/DataValidationException.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/service/HashService.java, src/main/java/faang/school/urlshortenerservice/util/BaseEncoder.java, src/main/java/faang/school/urlshortenerservice/util/HashGenerator.java, src/main/resources/application.yaml, src/test/java/faang/school/urlshortenerservice/service/HashServiceTest.java, src/test/java/faang/school/urlshortenerservice/util/BaseEncoderTest.java, src/test/java/faang/school/urlshortenerservice/util/HashGeneratorTest.java
=> feature 55251

src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/config/executor/ExecutorConfig.java, src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlDto.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/exception/handler/GlobalExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/HashCleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/scheduler/HashGeneratorScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/utilities/UrlUtils.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/url_shortener_V001_initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> url shortener (without tests)

build.gradle.kts, src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/config/asyncconfig/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/config/executerservice/ExecutorServiceConfig.java, src/main/java/faang/school/urlshortenerservice/config/redis/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/OriginalUrlDto.java, src/main/java/faang/school/urlshortenerservice/dto/ShortUrlDto.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/UrlAssociation.java, src/main/java/faang/school/urlshortenerservice/exception/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/localcache/HashCache.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/main/resources/db/changelog/db.changelog-master.yaml, src/main/resources/db/changelog/init.sql, src/test/java/faang/school/urlshortenerservice/controller/UrlControllerTest.java, src/test/java/faang/school/urlshortenerservice/encoder/Base62EncoderTest.java, src/test/java/faang/school/urlshortenerservice/generator/HashGeneratorTest.java, src/test/java/faang/school/urlshortenerservice/repository/UrlRepositoryTest.java, src/test/java/faang/school/urlshortenerservice/scheduler/CleanerSchedulerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceTest.java
(Без теста) Выполнил все задачи по сокращателю URL и теперь собираюсь сделать слияние в свою основную ветку.
=> URL shortener

src/main/java/faang/school/urlshortenerservice/ServiceTemplateApplication.java, src/main/java/faang/school/urlshortenerservice/advice/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/config/threadpool/ThreadPoolConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlRequest.java, src/main/java/faang/school/urlshortenerservice/dto/UrlResponse.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/service/HashCacheService.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/utils/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/utils/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/utils/HashCache.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/url_shortener_V000_initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/urlshortenerservice/ServiceTemplateApplicationTests.java
Задачи:
Создать структуру БД
Работа с базой(HashRepository)
Генерация списка хэшей
=> db structure + HashRepository + Base62Encoder

src/main/java/faang/school/urlshortenerservice/entity/Hash.java, src/main/java/faang/school/urlshortenerservice/entity/Url.java, src/main/resources/db/changelog/changeset/V001_shortener_initial.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Created tables url, hash, sequence unique_number_seq
=> voldemarmv-BJS2-78484

src/main/java/faang/school/urlshortenerservice/cache/HashCache.java, src/main/java/faang/school/urlshortenerservice/config/AsyncConfig.java, src/main/java/faang/school/urlshortenerservice/config/ExecutorConfig.java, src/main/java/faang/school/urlshortenerservice/config/RedisConfig.java, src/main/java/faang/school/urlshortenerservice/controller/UrlController.java, src/main/java/faang/school/urlshortenerservice/dto/UrlRequestDto.java, src/main/java/faang/school/urlshortenerservice/dto/UrlResponseDto.java, src/main/java/faang/school/urlshortenerservice/encoder/Base62Encoder.java, src/main/java/faang/school/urlshortenerservice/exception/CacheRefillException.java, src/main/java/faang/school/urlshortenerservice/exception/DatabaseAccessException.java, src/main/java/faang/school/urlshortenerservice/exception/ErrorMessages.java, src/main/java/faang/school/urlshortenerservice/exception/HashGenerationException.java, src/main/java/faang/school/urlshortenerservice/exception/InvalidUrlException.java, src/main/java/faang/school/urlshortenerservice/exception/UrlExceptionHandler.java, src/main/java/faang/school/urlshortenerservice/exception/UrlNotFoundException.java, src/main/java/faang/school/urlshortenerservice/generator/HashGenerator.java, src/main/java/faang/school/urlshortenerservice/repository/HashRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlCacheRepository.java, src/main/java/faang/school/urlshortenerservice/repository/UrlRepository.java, src/main/java/faang/school/urlshortenerservice/scheduler/CleanerScheduler.java, src/main/java/faang/school/urlshortenerservice/service/UrlService.java, src/main/java/faang/school/urlshortenerservice/service/UrlServiceImpl.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/url_V001__create_url_shortener.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/urlshortenerservice/scheduler/CleanerSchedulerTest.java, src/test/java/faang/school/urlshortenerservice/service/UrlServiceImplTest.java
https://faang-school.atlassian.net/browse/BJS2-78862
=> URL Shortener by who1s1tt
